<?php
/**
 * 現行ホームページと同じ初期値。
 * 管理画面で未保存の項目は、すべてここを使います。
 */
if (!defined('ABSPATH')) {
    exit;
}

function chuboya_defaults() {
    return array(
        /* SEO */
        'seo_title' => '中房家｜淡路・菅原の中華料理・大衆居酒屋｜うまいもんを、腹いっぱい。',
        'seo_description' => '大阪市東淀川区菅原の中房家。中華料理から手作りの一品料理まで、ランチも晩ごはんも気軽に楽しめる大衆居酒屋です。料理の豊富さ、ボリューム、コストパフォーマンス、温かい接客が魅力。JR淡路駅から徒歩圏、淡路周辺で食事・飲みのお店をお探しの方へ。',
        'seo_og_title' => '中房家｜淡路・菅原の中華料理・大衆居酒屋',
        'seo_og_description' => 'うまいもんを、腹いっぱい。中華料理から手作りの一品料理まで。ランチも晩ごはんも、ちょっと一杯も。淡路・菅原の大衆居酒屋。',

        /* 基本情報 */
        'shop_name' => '中房家',
        'shop_kana' => 'ちゅうぼうや',
        'shop_logo_sub' => '淡路・菅原の中華・大衆居酒屋',
        'phone_display' => '06-6990-5578',
        'address' => '大阪市東淀川区菅原7-14-2',
        'nearest' => 'JR淡路駅から約522m',
        'genre' => '中華料理・鳥料理・手作り一品料理／大衆居酒屋',
        'hours' => '要確認',
        'holiday' => '要確認',
        'parking' => '要確認',
        'payment' => '要確認',
        'reserve' => 'お電話にて（受付時間・条件は要確認）',
        'zip_note' => '郵便番号 要確認',
        'map_query' => '大阪市東淀川区菅原7-14-2',
        'map_note' => 'JR淡路駅から少し歩きます。駅からの徒歩ルート写真を追加すると、初めての方が迷いません。',
        'map_note_chip' => '写真素材要追加',
        'footer_desc' => '中華料理・鳥料理・手作り一品料理／淡路・菅原の大衆居酒屋',
        'copyright' => '© 中房家',
        'nav_tel_label' => 'お問い合わせ・ご予約',

        /* ファーストビュー */
        'hero_eyebrow' => '大阪市東淀川区菅原・JR淡路駅から徒歩圏',
        'hero_title_1' => 'うまいもんを、',
        'hero_title_2' => '腹いっぱい。',
        'hero_lead' => "中華料理から手作りの一品料理まで。\nランチも、晩ごはんも、ちょっと一杯も。\n気取らず楽しめる、淡路・菅原の大衆居酒屋「中房家」。",
        'hero_cta_menu' => 'お品書きを見る',
        'hero_cta_tel' => '電話する',
        'hero_strip_1' => '中華料理・鳥料理',
        'hero_strip_2' => '手作りの一品料理',
        'hero_strip_3' => 'ランチ／夜営業',
        'hero_strip_4' => 'ひとりでも、みんなでも',
        'hero_alt' => '夜の中房家の外観と看板（大阪市東淀川区菅原）',

        /* 中房家とは */
        'about_label' => '中房家とは',
        'about_heading_1' => 'お腹いっぱいだけじゃない。',
        'about_heading_2' => 'また来たくなる、',
        'about_heading_3' => '街の中房家。',
        'about_p1' => 'しっかり食べたい日も、ちょっと飲みたい日も。中房家は、中華料理から手作りの一品料理まで、気軽に楽しめる淡路・菅原の大衆居酒屋です。',
        'about_p2' => '「美味しかった」だけじゃなく、「店員さんが元気」「また来たい」。そんな声をいただけることも、中房家が大切にしていることのひとつです。',
        'about_note' => '※店舗としての正式なごあいさつ文は、店主様の言葉に差し替え予定です。',
        'about_note_chip' => '1',
        'about_staff_caption' => '店内・スタッフ',
        'about_staff_alt' => '厨房で調理する中房家のスタッフ',
        'about_exterior_caption' => '外観',
        'about_exterior_alt' => '中房家の外観・店頭の様子',

        /* 選ばれる理由 */
        'reasons_label' => 'Why 中房家',
        'reasons_heading' => '中房家が、選ばれる理由。',
        'reason1_title' => 'うまい',
        'reason1_text' => '中華料理から手作りの一品料理まで。「今日は何を食べよう？」と迷うことまで楽しめる、料理の幅広さ。',
        'reason1_alt' => '揚げたての唐揚げ',
        'reason2_title' => '腹いっぱい',
        'reason2_text' => 'しっかり食べたい日にうれしい、ボリュームとコストパフォーマンス。「今日はガッツリいきたい」に応えます。',
        'reason2_alt' => 'ボリュームのある料理の盛り合わせ',
        'reason3_title' => '人があったかい',
        'reason3_text' => '元気な声掛けと、気持ちのいい接客。料理だけじゃないところが、通いたくなる理由になっています。',
        'reason3_alt' => '笑顔で料理とドリンクを運ぶスタッフ',

        /* お品書き */
        'menu_label' => 'お品書き',
        'menu_heading' => '今日は、何食べる？',
        'menu_lead' => "中華料理から一品料理まで、いろいろ選べるのが中房家。\n今日はご飯もの、今日は麺、今日はみんなで一品料理。その日の気分で、好きな一皿を。",
        'menu_name_1' => '炒飯',
        'menu_price_1' => '要確認',
        'menu_name_2' => '天津麺',
        'menu_price_2' => '要確認',
        'menu_name_3' => '麻婆豆腐',
        'menu_price_3' => '要確認',
        'menu_name_4' => '酢豚',
        'menu_price_4' => '要確認',
        'menu_name_5' => '唐揚げ',
        'menu_price_5' => '要確認',
        'menu_name_6' => 'あんかけ焼きそば',
        'menu_price_6' => '要確認',
        'menu_name_7' => '汁なし担々麺',
        'menu_price_7' => '要確認',
        'menu_name_8' => 'ラーメン',
        'menu_price_8' => '要確認',
        'menu_more' => 'ほかにも手作りの一品料理を多数',
        'menu_note' => '※上記は口コミで名前が挙がっている料理です。現在のお品書き・価格は店舗確認後に掲載します。',
        'menu_note_chip' => '1',
        'menu_main_caption' => '看板の一皿',
        'menu_main_alt' => '中房家の人気料理・炒飯',
        'menu_noodles_caption' => '麺もの',
        'menu_noodles_alt' => '野菜と海老をのせた麺料理',
        'menu_ippin_caption' => '一品料理',
        'menu_ippin_alt' => '一品料理の餃子',

        /* ランチ */
        'lunch_label' => 'Lunch',
        'lunch_heading' => '昼は、しっかり。',
        'lunch_text' => '「今日はガッツリ食べたい」。そんな日のお昼にも、中房家。日替わりランチや定食、麺・ご飯ものなど、しっかり食べたい方に楽しんでいただけるランチをご用意しています。',
        'lunch_hours_label' => 'ランチ営業時間',
        'lunch_hours' => '要確認',
        'lunch_contents_label' => 'ランチの内容',
        'lunch_contents' => '日替わりランチ・定食・麺・ご飯もの',
        'lunch_contents_chip' => '1',
        'lunch_price_label' => '価格',
        'lunch_price' => '要確認',
        'lunch_note' => '※口コミでは1,000円前後でのランチ利用例が確認できます（金額は口コミ上の一例で、現在の価格は要確認）。',
        'lunch_cta' => '今日のランチを電話で確認する',
        'lunch_caption' => 'ランチ',
        'lunch_alt' => '唐揚げの定食',

        /* 夜 */
        'night_label' => 'Dinner',
        'night_heading_1' => '夜は、',
        'night_heading_2' => '食べて、飲んで、',
        'night_heading_3' => '楽しもう。',
        'night_lead' => "晩ごはんとしてしっかり食べるのも、仲間と料理を囲んで飲むのも。\n中華料理や手作りの一品料理を楽しみながら、気取らず過ごせるのが中房家です。",
        'night_caption' => '夜の店内',
        'night_alt' => '手書きの日本酒メニューと日本酒の瓶、一品料理',
        'drink_title' => '料理と一緒に、もう一杯。',
        'drink_text' => '料理に合わせて、お酒も気軽に。口コミでは日本酒を楽しまれている声も確認できます。',
        'drink_1' => '日本酒',
        'drink_2' => 'その他ドリンク',
        'drink_2_chip' => '1',
        'drink_note' => '※ドリンクの詳しいラインナップ・価格は店舗確認後に掲載します。',
        'night_note' => '※口コミでは夜の利用で2,000〜3,000円程度という声が確認できます（金額は口コミ上の一例で、現在の価格は要確認）。',

        /* 店内 */
        'seats_label' => '店内・利用シーン',
        'seats_heading_1' => 'ひとりでも、',
        'seats_heading_2' => '家族でも、',
        'seats_heading_3' => 'みんなでも。',
        'seats_lead' => "ふらっと一人で。仕事のあとに仲間と。休日に家族で。\nどんな使い方でも肩ひじ張らずに過ごせるのが、街の大衆居酒屋のいいところです。",
        'scene_solo_title' => 'ひとりで、さっと一皿',
        'scene_solo_text' => '「今日は一人でしっかり食べたい」ときにも入りやすい、気負わない雰囲気です。',
        'scene_solo_alt' => 'ひとりでビールを楽しむ様子',
        'scene_family_title' => '家族で、いろいろ頼んで',
        'scene_family_text' => '料理の種類が多いので、それぞれ好きなものを頼めます。',
        'scene_family_alt' => 'テーブルを囲んで乾杯する家族連れ',
        'scene_group_title' => 'みんなで、囲んで飲んで',
        'scene_group_text' => '大人数でのご利用可否・席の種類は店舗へお問い合わせください。',
        'scene_group_alt' => 'ビールで乾杯するグループ',
        'seats_note' => '※席数・座敷・個室・宴会や貸切の対応は確認中です。',
        'seats_note_chip' => '1',

        /* お客様の声 */
        'voices_label' => 'お客様の声',
        'voices_heading_1' => '「また来たい」が、',
        'voices_heading_2' => 'うれしい。',
        'voices_lead' => '口コミでくり返しお褒めいただいているのは、この5つです。',
        'voice1_title' => 'コストパフォーマンス',
        'voice1_text' => '「この内容でこの価格」という評価を多くいただいています。',
        'voice2_title' => 'ボリューム',
        'voice2_text' => 'しっかり食べたい方から「お腹いっぱいになる」との声が続いています。',
        'voice3_title' => '料理のおいしさ',
        'voice3_text' => '中華から一品料理まで、味への評価をいただいています。',
        'voice4_title' => 'メニューの豊富さ',
        'voice4_text' => '「選ぶのが楽しい」と言っていただけることも多いです。',
        'voice5_title' => 'スタッフの接客',
        'voice5_text' => '元気な声掛けや気持ちのいい応対に、うれしい言葉をいただいています。',
        'voices_note' => '※Googleマップ・食べログ等でいただいた口コミの傾向をまとめたものです。実際の口コミ本文を掲載する場合は、出典と掲載可否を確認のうえ差し替えます。',
        'voices_note_chip' => '1',

        /* アクセス見出し */
        'access_label' => 'アクセス',
        'access_heading' => '中房家へのご案内',
        'access_name_label' => '店名',
        'access_name' => '中房家（ちゅうぼうや）',
        'access_maps_link' => 'Googleマップで開く',

        /* FAQ */
        'faq_label' => 'よくある質問',
        'faq_heading_1' => '来店前に、',
        'faq_heading_2' => 'よくいただくご質問。',
        'faq_q_1' => '予約はできますか？',
        'faq_a_1' => 'お電話でのご予約を承っています。受付時間や人数の条件については、店舗へご確認ください。',
        'faq_a_1_chip' => '1',
        'faq_q_2' => 'ひとりでも利用できますか？',
        'faq_a_2' => 'お一人でのご利用も歓迎しています。詳しい席の状況は店舗へお問い合わせください。',
        'faq_a_2_chip' => '1',
        'faq_q_3' => 'ランチはありますか？',
        'faq_a_3' => '日替わりランチや定食などのランチ営業を行っています。現在の内容・時間は店舗へご確認ください。',
        'faq_a_3_chip' => '1',
        'faq_q_4' => 'テイクアウトはできますか？',
        'faq_a_4' => '過去にテイクアウトのご利用実績はありますが、現在の対応状況は店舗へご確認ください。',
        'faq_a_4_chip' => '1',
        'faq_q_5' => '駐車場はありますか？',
        'faq_a_5' => '確認中です。',
        'faq_a_5_chip' => '1',
        'faq_q_6' => '大人数でも利用できますか？',
        'faq_a_6' => 'ご利用可能な人数・お席については店舗へお問い合わせください。',
        'faq_a_6_chip' => '1',
        'faq_q_7' => '支払いにカードや電子マネーは使えますか？',
        'faq_a_7' => '確認中です。',
        'faq_a_7_chip' => '1',

        /* CTA */
        'cta_title_1' => '今日は、',
        'cta_title_2' => '中房家で腹いっぱい。',
        'cta_lead' => "美味しいものを気軽に食べたい日も、みんなで楽しく飲みたい日も。\n淡路・菅原の中房家へ。",
        'cta_tel' => '電話する',
        'cta_access' => 'アクセスを見る',
        'fixed_tel' => '電話する',
        'fixed_access' => 'アクセス',

        /* 画像ID（0 = テーマ同梱の初期写真を使う） */
        'photo_hero' => 0,
        'photo_about_staff' => 0,
        'photo_about_exterior' => 0,
        'photo_reason_food' => 0,
        'photo_reason_volume' => 0,
        'photo_reason_staff' => 0,
        'photo_menu_main' => 0,
        'photo_menu_noodles' => 0,
        'photo_menu_ippin' => 0,
        'photo_lunch' => 0,
        'photo_night' => 0,
        'photo_scene_solo' => 0,
        'photo_scene_family' => 0,
        'photo_scene_group' => 0,
    );
}

/**
 * 管理画面の写真スロット定義
 */
function chuboya_photo_slots() {
    return array(
        'photo_hero' => array(
            'label' => 'ファーストビュー（外観）',
            'file' => 'hero.jpg',
            'fallback' => 'dark',
            'hint' => '画面いっぱいに表示されます。店名の看板が中央寄りになると見やすいです。',
        ),
        'photo_about_staff' => array(
            'label' => '中房家とは：店内・スタッフ',
            'file' => 'about-staff.jpg',
            'fallback' => 'light',
            'hint' => '縦長（3:4）で表示されます。',
        ),
        'photo_about_exterior' => array(
            'label' => '中房家とは：外観（小）',
            'file' => 'about-exterior.jpg',
            'fallback' => 'light',
            'hint' => '画面幅 900px 以上でのみ表示される既存デザインです。',
        ),
        'photo_reason_food' => array(
            'label' => '選ばれる理由 01「うまい」',
            'file' => 'reason-food.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
        'photo_reason_volume' => array(
            'label' => '選ばれる理由 02「腹いっぱい」',
            'file' => 'reason-volume.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
        'photo_reason_staff' => array(
            'label' => '選ばれる理由 03「人があったかい」',
            'file' => 'reason-staff.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
        'photo_menu_main' => array(
            'label' => 'お品書き：主役（炒飯など）',
            'file' => 'menu-main.jpg',
            'fallback' => 'light',
            'hint' => '横長（4:3）で大きく表示されます。',
        ),
        'photo_menu_noodles' => array(
            'label' => 'お品書き：麺料理',
            'file' => 'menu-noodles.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
        'photo_menu_ippin' => array(
            'label' => 'お品書き：一品料理',
            'file' => 'menu-ippin.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
        'photo_lunch' => array(
            'label' => 'ランチ',
            'file' => 'lunch.jpg',
            'fallback' => 'light',
            'hint' => '横長で表示されます。',
        ),
        'photo_night' => array(
            'label' => '夜の楽しみ方',
            'file' => 'night.jpg',
            'fallback' => 'dark',
            'hint' => '夜の店内・料理・お酒の雰囲気。',
        ),
        'photo_scene_solo' => array(
            'label' => '利用シーン：一人利用',
            'file' => 'scene-solo.jpg',
            'fallback' => 'light',
            'hint' => 'PCでは横長（21:9）になります。',
        ),
        'photo_scene_family' => array(
            'label' => '利用シーン：家族利用',
            'file' => 'scene-family.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
        'photo_scene_group' => array(
            'label' => '利用シーン：グループ利用',
            'file' => 'scene-group.jpg',
            'fallback' => 'light',
            'hint' => '正方形で表示されます。',
        ),
    );
}
